name: Model Training and Deployment

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Triggers the workflow on pull request to the main branch

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Train model
      run: |
        python train_model.py  # Replace with your actual model training script

    - name: Run tests
      run: |
        python -m unittest discover  # Replace with your test command

    - name: Deploy model (optional step, depending on your deployment strategy)
      run: |
        # Add deployment commands here (e.g., push to cloud storage or deploy to API)
